### ISSUE TITLE
Wow!  Amazing quality.... thanks for posting a screenshot!

### ISSUE THREAD

**Issue by PySimpleGUI** [mizosoft/image-rest-enh#1]
Congratulations on the results of your project!

Stunning images you've posted in your readme.  

![image](https://user-images.githubusercontent.com/46163555/177186112-2a7da721-a7eb-4e05-a495-70e638f34c1d.png)

Thank you for posting screenshots of your GUI.... would be nice to get a mention that it's built with PySimpleGUI, but not a huge thing.  I'm simply happy you posted what you created.  It's really beautiful work!

**Comment by mizosoft** [comment]
Thanks! I've linked to PySimpleGUI in the README. It's a very nice library and very easy to use!

**Comment by PySimpleGUI** [comment]
Thank you for the mention!  And thank you for the kind words... I'm happy you found it an enjoyable experience.  I would like to mention your repo in a PySimpleGUI announcement if that's OK with you.  I've got a colorized repo that's fun to play with, but your example images are stunning.  They make what I've got running look like crayons were used.

**Comment by mizosoft** [comment]
Glad you like the results! I'm OK with an announcement but please give due credit to the awesome work this project uses:

* [Bring Old Photos Back To LIfe](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life)
* [GPEN](https://github.com/yangxy/GPEN)
* [DeOldify](https://github.com/jantic/DeOldify)

Also, interesting colorization repo you've got :)

**Comment by jalubaas123** [comment]
python version plz, does it need CUDA
