### ISSUE TITLE
Announced and posted fully populated project...

### ISSUE THREAD

**Issue by PySimpleGUI** [mizosoft/image-rest-enh#3]
Hi!

As we have been discussing in another issue, I have publicly announced the availability of your project to be downloaded including the models.  You'll find the information in the Announcements issue on my GitHub:
https://github.com/PySimpleGUI/PySimpleGUI/issues/142

To make it very easy to remember, I created a subnet from the PySimpleGUI.org domain:
mizosoft.ImageRestoration.PySimpleGUI.org

Going there will start the download of the 4.5 GB ZIP file.

Thank you again, so very much, for making this tool.  I'm sure a number of other people will have similar personally moving experiences with it.

**Comment by mizosoft** [comment]
Hi Mike, this is really nice of you! Thanks for the announcement & hosting the files! I hope it does benefit other people ;) I'll add the link in the README.

**Comment by PySimpleGUI** [comment]
Thank you!

![image](https://user-images.githubusercontent.com/46163555/179430966-bc434523-6a4c-41b3-bfdf-053323fe237a.png)

And it was very nice of you to create this project, post it for everyone to use, to give me the instructions on how to download the models, .....

I was just completing my half of the circle.  

I just made 2 changes BTW.

I changed the filename `gui.pyw` to  `RunMeForGUI.pyw` to make it really clear what users should do once the ZIP is downloaded and upzipped.


----------------

The other was that I added `os.chdir` as the code seems to assume that the working directory is where the files are.  If I launch the .pyw file from another location, I got errors saying it can't find the weights, etc.

```python
def modify(image_file, colorize=False, scratches=False):
    # parser = argparse.ArgumentParser()
    # parser.add_argument("--input_folder", type=str, default="input", help="Input folder")
    # parser.add_argument("--output_folder", type=str, default="output/soka", help="Output folder")
    # parser.add_argument("--run_mode", type=int, default=1, choices=range(1, 5), help= "Setting run mode, 1-> ENHANCE_RESTORE 2->RESTORE_ENHANCE 3->RESTORE_ONLY 4->ENHANCE_ONLY")
    # parser.add_argument("--sr_scale", type=int, default=4)
    # parser.add_argument("--hr_quality", action='store_true')
    # parser.add_argument("--hr_restore", action='store_true')
    # args = parser.parse_args()

    print(f'handling input: {image_file}')
    os.chdir(os.path.dirname(__file__))

```
